
  LDFunctionUMTAddTeam:
    Type: AWS::Serverless::Function
    DependsOn: LDLayerUMTEnvs
    Properties:
      FunctionName: umt-add-team
      CodeUri: lambda/functions/umt-add-team/
      Role: !ImportValue ARV-IARoleARVLambdaARN
      Layers:
        - !Ref LDLayerUMTEnvs
