
  LDFunctionUMTNearTeams:
    Type: AWS::Serverless::Function
    DependsOn: LDLayerUMTEnvs
    Properties:
      FunctionName: umt-near-teams
      CodeUri: !Join [ "/", [ !Ref HostRoot, "lambda/functions/umt-near-teams/" ] ]
      Role: !ImportValue ARV-IARoleARVLambdaARN
      Layers:
        - !Ref LDLayerUMTEnvs
