
  LDFunctionUMTAddMatchChat:
    Type: AWS::Serverless::Function
    DependsOn:
      - LDLayerUMTEnvs
      - LDLayerUMTExt
    Properties:
      FunctionName: umt-add-matchchat
      CodeUri: !Join [ "/", [ !Ref HostRoot, "lambda/functions/umt-add-matchchat/" ] ]
      Role: !ImportValue ARV-IARoleARVLambdaARN
      Layers:
        - !Ref LDLayerUMTEnvs
        - !Ref LDLayerUMTExt
