# Continuous Deployment
name: CD

on:
  push:
    branches: [ develop ]

jobs:

  deploy:
    name: Despliegue
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Despliegue en AWS
        if: github.ref == 'refs/heads/develop'
        env:
          # GLOBAL
          ENV_SO: ${{ secrets.ENV_SO }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_DEV }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_DEV }}
          AWS_R53_UMT_DOMAIN: ${{ secrets.AWS_R53_UMT_DOMAIN_DEV }}
          # UMT
          AWS_S3_WEB_BUCKET: ${{ secrets.AWS_S3_WEB_BUCKET_DEV }}
          AWS_S3_ARTIFACTS_BUCKET: ${{ secrets.AWS_S3_ARTIFACTS_BUCKET_DEV }}
        run: |
          chmod +x deploy.sh
          ./deploy.sh