# ==============================
# Continuous Deployment
# ==============================
name: CD

on:
  pull_request:
    types: [ closed ] 
    branches: [ develop ]

jobs:

  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # ------------------------------
      # Run deploy DEV
      # ------------------------------
      - name: Run deploy DEV
        if: github.base_ref == 'develop'
        env:
          # GLOBAL
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_DEV }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_DEV }}
          AWS_R53_UMT_DOMAIN: ${{ secrets.AWS_R53_UMT_DOMAIN_DEV }}
          # UMT
          AWS_S3_WEB_BUCKET: ${{ secrets.AWS_S3_WEB_BUCKET_DEV }}
          AWS_S3_ARTIFACTS_BUCKET: ${{ secrets.AWS_S3_ARTIFACTS_BUCKET_DEV }}
        run: |
          chmod +x deploy.sh
          docker-compose up deploy-executor