# ==============================
# Continuous Integration
# ==============================
name: CI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches:
      - '**'

jobs:

  test:
    name: Testing on AWS Lambda
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # ------------------------------
      # Run tests DEV
      # ------------------------------
      - name: Run tests DEV
        if: |
          contains(github.ref, 'feature') ||
          github.ref == 'refs/heads/develop' ||
          github.base_ref == 'develop'
        env:
          # GLOBAL
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_DEV }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_DEV }}
          AWS_R53_UMT_DOMAIN: ${{ secrets.AWS_R53_UMT_DOMAIN_DEV }}
          # UMT
          AWS_S3_WEB_BUCKET: ${{ secrets.AWS_S3_WEB_BUCKET_DEV }}
          AWS_S3_ARTIFACTS_BUCKET: ${{ secrets.AWS_S3_ARTIFACTS_BUCKET_DEV }}
        run: |
          chmod +x testing.sh
          docker-compose up --exit-code-from test-executor test-executor